# Basics Of Pandas

### Why Pandas?
#### -Flexibility with Python
#### -Working with large and big data

In [4]:
# Importing pandas module

import pandas as pd

# Reading dataset
df_copy = pd.read_csv('pokedex.csv')
df = pd.read_csv('pokemon_data.csv')

### Reading Data in Pandas

In [19]:
## Reading Headers
df.columns

## Reading Columns
df['Name'] # This can be achieved using df.Name
df[['#', 'Type 1']]
df['Name'][0:5]   


## Reading Rows
df.iloc[1:4] # iloc means integer locations
df.iloc[[1,5,7]]
df.iloc[1:10:2]

# Iterating through each row
'''
for index, row in df.iterrows():
    print(index, row) # To specific columns:- row['column_name']. list is also supported
'''

## Reading specific rows and columns (R,C)
df.iloc[2,1]

# loc function is used for more textual based functionality
df.loc[df['Type 1'] == 'Fire']
df.loc[(df['Type 1'] == 'Fire') & (df['HP'] >= 50)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Sorting/Describing Data

In [ ]:
df.describe()

df.sort_values('Name', ascending=False)
df.sort_values(['Type 1', 'HP'], ascending=[1, 1])

### Making Changes To The Data

In [27]:
df['Total'] = df.iloc[:,4:10].sum(axis=1)

cols = list(df.columns)
# You can rearrange the columns
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

### Saving Data (Exporting into Desired Format)

In [ ]:
df.to_csv('modified.csv', index=False, sep='\t')
df.to_excel('modified.xlsx')

### Filtering Data

In [50]:
# &, |, >, <, <=, >=

df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]
df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]

new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

new_df.reset_index(drop=True, inplace=True)
# new_df.reset_index(drop=True)
new_df

df.loc[df['Name'].str.contains('Mega')]
df.loc[-df['Name'].str.contains('Mega')]

## Importing and using regex 
import re
df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]
df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

### Conditional Changes

In [53]:
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
df.loc[df['Type 1'] == 'Fire', 'Legendary'] = True

# modifying multiple columns
df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = 'Test value' # or modify individual column :- ['test value1', 'testvalue2']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,6,True,600

### Aggregate Statistics (Groupby)

In [63]:
df.groupby(['Type 1']).sum(numeric_only=True)
df.groupby(['Type 1']).mean(numeric_only=True).sort_values('Attack', ascending=False)

df.groupby(['Type 1', 'Type 2']).count()

                  #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric   2     2   2       2        2        2        2      2
       Fighting   2     2   2       2        2        2        2      2
       Fire       2     2   2       2        2        2        2      2
       Flying    14    14  14      14       14       14       14     14
       Ghost      1     1   1       1        1        1        1      1
...              ..   ...  ..     ...      ...      ...      ...    ...
Water  Ice        3     3   3       3        3        3        3      3
       Poison     3     3   3       3        3        3        3      3
       Psychic    5     5   5       5        5        5        5      5
       Rock       4     4   4       4        4        4        4      4
       Steel      1     1   1       1        1        1        1      1

                 Generation  Legendary  Total
Type 1 Type 2
Bug    Electric           2          2      2
       Fighting           2          2      2
       Fire               2          2      2
       Flying            14         14     14
       Ghost              1          1      1
...                     ...        ...    ...
Water  Ice                3          3      3
       Poison             3          3      3
       Psychic            5          5      5
       Rock               4          4      4
       Steel              1          1      1

[136 rows x 11 columns]

### Working with large amounts of data

In [ ]:
# loading dataframe in chunks
new_df = pd.DataFrame(columns=df.columns)
for df in pd.read_csv('pokemon_data.csv',chunksize=5):
    results = df.groupby(['Type 1']).count()

    new_df = pd.concat([new_df, results])
new_df

# More Information on Pandas

In [65]:
import pandas as pd

### Working with Series in Pandas

In [71]:
# Creating series
    # series handles one dimensional array
data = pd.Series([2,3,4,5], index=['a', 'b', 'c', 'd'])
data.index


# indexing is done in an explicit manner
data['a':'c'] # last element is inclusive


# Creating series from dictionary
grades_dict = {'A':4, 'B':3.5, 'C':3,'D':2.5, 'E':2}
grades = pd.Series(grades_dict)
marks_dict = {'A':40, 'B':75, 'C':93,'D':88, 'E':56}
marks = pd.Series(marks_dict)

grades
marks

A    40
B    75
C    93
D    88
E    56
dtype: int64

### Working with DataFrame

In [78]:
df = pd.DataFrame({'Marks':marks, 'Grades':grades})
df

df.T
df.values
df[['Marks', 'Grades']][0:2]
df.values[1,1]

3.5

### Indexing in Pandas
#####   data[1] # explicit index, use loc instead
#####   data[1:3] # implicit index, use iloc instead

In [ ]:
# Changing columns

df.rename(columns={'Old1':'new1'}, implace=True)